name: ebay-config

# OAuth Access Tokens - https://developer.ebay.com/api-docs/static/oauth-tokens.html

# UPDATE the values in this file, before running the tests
api.sandbox.ebay.com:
    appid: EricaAnd-GarboSel-SBX-6a6d4ee64-721b5440
    certid: SBX-a6d4ee641e42-af54-48c3-a764-f4f7
    devid: 502765d1-74be-4ad9-bab0-1afc624ae3d2
    redirecturi: Erica_Anderson-EricaAnd-GarboS-qjioz

api.ebay.com:
    appid: EricaAnd-GarboSel-PRD-2dfed6342-48382a6f
    certid: PRD-dfed6342f5c7-fdc2-439c-9cf3-b112
    devid: 502765d1-74be-4ad9-bab0-1afc624ae3d2
    redirecturi: Erica_Anderson-EricaAnd-GarboS-dinttmk
